#!/bin/bash

if [ $# -ne 1 ]
then
	echo need only one new project name
	exit
fi

projectName=$1

mkdir $projectName
mkdir $projectName/preproduction
mkdir $projectName/production
mkdir $projectName/postproduction
mkdir $projectName/completed
